name: flutter_interactive_keyboard
description: A flutter plugin to dismiss the keyboard interactively.
version: 0.0.1
author: Mattia Crovero
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.ujiboo.flutter_interactive_keyboard
    pluginClass: InteractiveKeyboardNativePlugin